import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

type Lang = "es" | "en";

function money(value: number, currency = "USD") {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
  }).format(Number(value || 0));
}

function formatDate(value: string | null | undefined, lang: Lang) {
  if (!value) return "-";
  return new Date(value).toLocaleDateString(lang === "es" ? "es-US" : "en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function copy(lang: Lang) {
  return lang === "en"
    ? {
        invoice: "INVOICE",
        from: "FROM",
        billTo: "BILL TO",
        issue: "Issue date",
        due: "Due date",
        status: "Status",
        payOnline: "Pay online",
        scanToPay: "Scan to pay",
        desc: "Description",
        qty: "Qty",
        price: "Price",
        total: "Total",
        subtotal: "Subtotal",
        tax: "Tax",
        notes: "Notes",
        thanks: "Thank you for your business.",
        generated: "Generated by Tadeo Invoices",
      }
    : {
        invoice: "FACTURA",
        from: "DE",
        billTo: "PARA",
        issue: "Emisión",
        due: "Vencimiento",
        status: "Estado",
        payOnline: "Pagar online",
        scanToPay: "Escanea para pagar",
        desc: "Descripción",
        qty: "Cant.",
        price: "Precio",
        total: "Total",
        subtotal: "Subtotal",
        tax: "Impuestos",
        notes: "Notas",
        thanks: "Gracias por tu negocio.",
        generated: "Generado por Tadeo Invoices",
      };
}

async function drawImageFromUrl({
  pdfDoc,
  page,
  url,
  x,
  y,
  maxWidth,
  maxHeight,
}: {
  pdfDoc: PDFDocument;
  page: any;
  url: string;
  x: number;
  y: number;
  maxWidth: number;
  maxHeight: number;
}) {
  try {
    const res = await fetch(url, { cache: "no-store" });
    if (!res.ok) return false;

    const bytes = await res.arrayBuffer();
    const lower = url.toLowerCase();

    const img =
      lower.includes(".png") || lower.includes("image/png")
        ? await pdfDoc.embedPng(bytes)
        : await pdfDoc.embedJpg(bytes);

    let width = img.width;
    let height = img.height;

    const ratio = Math.min(maxWidth / width, maxHeight / height);
    width *= ratio;
    height *= ratio;

    page.drawImage(img, {
      x,
      y: y + (maxHeight - height),
      width,
      height,
    });

    return true;
  } catch {
    return false;
  }
}

export async function GET(
  req: Request,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await context.params;
    const url = new URL(req.url);
    const lang: Lang = url.searchParams.get("lang") === "en" ? "en" : "es";
    const t = copy(lang);

    const { data: invoice, error } = await supabaseAdmin
      .from("invoices")
      .select("*, invoice_items(*)")
      .eq("id", id)
      .single();

    if (error || !invoice) {
      return NextResponse.json(
        { error: "Factura no encontrada" },
        { status: 404 }
      );
    }

    const { data: profile } = await supabaseAdmin
      .from("profiles")
      .select(
        "company_name, company_email, company_phone, company_address, logo_url"
      )
      .eq("id", invoice.user_id)
      .single();

    const currency = invoice.currency || "USD";
    const siteUrl =
      process.env.NEXT_PUBLIC_SITE_URL ||
      "https://tadeo-invoices-clean-pdw3.vercel.app";

    const publicPayUrl = invoice.public_token
      ? `${siteUrl}/public-invoice/${invoice.public_token}/pay`
      : `${siteUrl}/invoice/${invoice.id}`;

    const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(
      publicPayUrl
    )}`;

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([612, 792]);

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const navy = rgb(0.02, 0.05, 0.15);
    const blue = rgb(0.15, 0.39, 0.92);
    const softBlue = rgb(0.93, 0.96, 1);
    const light = rgb(0.985, 0.99, 1);
    const line = rgb(0.86, 0.9, 0.95);
    const muted = rgb(0.39, 0.46, 0.57);
    const white = rgb(1, 1, 1);
    const green = rgb(0.05, 0.6, 0.35);
    const amber = rgb(0.82, 0.48, 0.08);

    page.drawRectangle({
      x: 0,
      y: 0,
      width: 612,
      height: 792,
      color: light,
    });

    page.drawCircle({
      x: 548,
      y: 745,
      size: 140,
      color: rgb(0.9, 0.95, 1),
      opacity: 0.75,
    });

    page.drawCircle({
      x: 30,
      y: 40,
      size: 120,
      color: rgb(0.93, 0.96, 1),
      opacity: 0.8,
    });

    const logoDrawn =
      profile?.logo_url &&
      (await drawImageFromUrl({
        pdfDoc,
        page,
        url: profile.logo_url,
        x: 44,
        y: 710,
        maxWidth: 145,
        maxHeight: 56,
      }));

    if (!logoDrawn) {
      page.drawText(profile?.company_name || "TADEO INVOICES", {
        x: 44,
        y: 742,
        size: 16,
        font: bold,
        color: navy,
      });

      page.drawText("Premium billing", {
        x: 44,
        y: 724,
        size: 9,
        font,
        color: muted,
      });
    }

    page.drawText(t.invoice, {
      x: 390,
      y: 728,
      size: 34,
      font: bold,
      color: navy,
    });

    page.drawText(`#${invoice.invoice_number || invoice.id}`, {
      x: 392,
      y: 704,
      size: 11,
      font,
      color: muted,
    });

    page.drawRectangle({
      x: 44,
      y: 674,
      width: 524,
      height: 1,
      color: line,
    });

    const companyName =
      profile?.company_name || invoice.company_name || "Tadeo Invoices";
    const companyEmail =
      profile?.company_email || invoice.company_email || "";
    const companyPhone =
      profile?.company_phone || invoice.company_phone || "";
    const companyAddress =
      profile?.company_address || invoice.company_address || "";

    page.drawText(t.from, {
      x: 44,
      y: 642,
      size: 9,
      font: bold,
      color: blue,
    });

    page.drawText(companyName, {
      x: 44,
      y: 622,
      size: 15,
      font: bold,
      color: navy,
    });

    page.drawText(companyEmail || "-", {
      x: 44,
      y: 604,
      size: 10,
      font,
      color: muted,
    });

    if (companyPhone) {
      page.drawText(companyPhone, {
        x: 44,
        y: 588,
        size: 10,
        font,
        color: muted,
      });
    }

    if (companyAddress) {
      page.drawText(String(companyAddress).slice(0, 54), {
        x: 44,
        y: 572,
        size: 10,
        font,
        color: muted,
      });
    }

    page.drawRectangle({
      x: 332,
      y: 560,
      width: 236,
      height: 92,
      color: white,
      borderColor: line,
      borderWidth: 1,
    });

    page.drawText(t.billTo, {
      x: 352,
      y: 628,
      size: 9,
      font: bold,
      color: blue,
    });

    page.drawText(invoice.client_name || "-", {
      x: 352,
      y: 608,
      size: 15,
      font: bold,
      color: navy,
    });

    page.drawText(invoice.client_email || "-", {
      x: 352,
      y: 590,
      size: 10,
      font,
      color: muted,
    });

    page.drawText(`${t.issue}: ${formatDate(invoice.issue_date, lang)}`, {
      x: 352,
      y: 570,
      size: 9,
      font,
      color: muted,
    });

    page.drawText(`${t.due}: ${formatDate(invoice.due_date, lang)}`, {
      x: 456,
      y: 570,
      size: 9,
      font,
      color: muted,
    });

    const status = String(invoice.status || "pending").toLowerCase();
    const statusColor = status === "paid" ? green : status === "pending" ? amber : muted;

    page.drawRectangle({
      x: 44,
      y: 510,
      width: 524,
      height: 36,
      color: white,
      borderColor: line,
      borderWidth: 1,
    });

    page.drawText(t.status, {
      x: 64,
      y: 524,
      size: 10,
      font: bold,
      color: muted,
    });

    page.drawCircle({
      x: 128,
      y: 529,
      size: 4,
      color: statusColor,
    });

    page.drawText(status.toUpperCase(), {
      x: 140,
      y: 524,
      size: 10,
      font: bold,
      color: statusColor,
    });

    page.drawText(t.payOnline, {
      x: 354,
      y: 524,
      size: 10,
      font: bold,
      color: blue,
    });

    page.drawText(publicPayUrl.slice(0, 34), {
      x: 430,
      y: 524,
      size: 8,
      font,
      color: muted,
    });

    let y = 460;

    page.drawRectangle({
      x: 44,
      y,
      width: 524,
      height: 34,
      color: navy,
    });

    page.drawText(t.desc, {
      x: 62,
      y: y + 12,
      size: 10,
      font: bold,
      color: white,
    });

    page.drawText(t.qty, {
      x: 310,
      y: y + 12,
      size: 10,
      font: bold,
      color: white,
    });

    page.drawText(t.price, {
      x: 372,
      y: y + 12,
      size: 10,
      font: bold,
      color: white,
    });

    page.drawText(t.total, {
      x: 500,
      y: y + 12,
      size: 10,
      font: bold,
      color: white,
    });

    y -= 36;

    const items = invoice.invoice_items || [];

    for (const item of items) {
      const qty = item.quantity ?? item.qty ?? 1;
      const price = item.unit_price ?? item.price ?? 0;
      const lineTotal =
        item.line_total ?? item.total ?? Number(qty) * Number(price);

      page.drawRectangle({
        x: 44,
        y: y - 10,
        width: 524,
        height: 34,
        color: white,
        borderColor: line,
        borderWidth: 0.5,
      });

      page.drawText(String(item.description || "-").slice(0, 42), {
        x: 62,
        y: y + 2,
        size: 10,
        font,
        color: navy,
      });

      page.drawText(String(qty), {
        x: 316,
        y: y + 2,
        size: 10,
        font,
        color: muted,
      });

      page.drawText(money(Number(price), currency), {
        x: 360,
        y: y + 2,
        size: 10,
        font,
        color: muted,
      });

      page.drawText(money(Number(lineTotal), currency), {
        x: 482,
        y: y + 2,
        size: 10,
        font: bold,
        color: navy,
      });

      y -= 34;

      if (y < 190) break;
    }

    const subtotal = Number(invoice.subtotal || 0);
    const tax = Number(invoice.tax_total ?? invoice.tax ?? 0);
    const total = Number(invoice.total || 0);

    page.drawRectangle({
      x: 330,
      y: 116,
      width: 238,
      height: 120,
      color: softBlue,
      borderColor: rgb(0.72, 0.82, 1),
      borderWidth: 1,
    });

    page.drawText(t.subtotal, {
      x: 350,
      y: 204,
      size: 10,
      font,
      color: muted,
    });

    page.drawText(money(subtotal, currency), {
      x: 456,
      y: 204,
      size: 10,
      font: bold,
      color: navy,
    });

    page.drawText(t.tax, {
      x: 350,
      y: 178,
      size: 10,
      font,
      color: muted,
    });

    page.drawText(money(tax, currency), {
      x: 456,
      y: 178,
      size: 10,
      font: bold,
      color: navy,
    });

    page.drawRectangle({
      x: 350,
      y: 158,
      width: 198,
      height: 1,
      color: line,
    });

    page.drawText(t.total.toUpperCase(), {
      x: 350,
      y: 132,
      size: 13,
      font: bold,
      color: navy,
    });

    page.drawText(money(total, currency), {
      x: 440,
      y: 130,
      size: 18,
      font: bold,
      color: blue,
    });

    await drawImageFromUrl({
      pdfDoc,
      page,
      url: qrUrl,
      x: 54,
      y: 128,
      maxWidth: 84,
      maxHeight: 84,
    });

    page.drawText(t.scanToPay, {
      x: 150,
      y: 184,
      size: 11,
      font: bold,
      color: navy,
    });

    page.drawText(publicPayUrl.slice(0, 48), {
      x: 150,
      y: 166,
      size: 8,
      font,
      color: muted,
    });

    if (invoice.notes) {
      page.drawText(t.notes, {
        x: 44,
        y: 104,
        size: 10,
        font: bold,
        color: navy,
      });

      page.drawText(String(invoice.notes).slice(0, 110), {
        x: 44,
        y: 88,
        size: 9,
        font,
        color: muted,
      });
    }

    page.drawText(t.thanks, {
      x: 44,
      y: 52,
      size: 10,
      font: bold,
      color: navy,
    });

    page.drawText(t.generated, {
      x: 44,
      y: 36,
      size: 8,
      font,
      color: muted,
    });

    const pdfBytes = await pdfDoc.save();
    const pdfBuffer = Buffer.from(pdfBytes);

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="invoice-${
          invoice.invoice_number || invoice.id
        }-${lang}.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF_ERROR", error);
    return NextResponse.json(
      { error: "No se pudo generar el PDF" },
      { status: 500 }
    );
  }
}