import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export const runtime = "nodejs";

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

type Lang = "en" | "es";

function money(value: number, currency = "USD") {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
  }).format(Number(value || 0));
}

function formatDate(value: string | null | undefined, lang: Lang) {
  if (!value) return "-";

  return new Date(value).toLocaleDateString(lang === "es" ? "es-US" : "en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function copy(lang: Lang) {
  return lang === "es"
    ? {
        invoice: "FACTURA",
        from: "DE",
        billTo: "PARA",
        issue: "Emisión",
        due: "Vencimiento",
        status: "Estado",
        desc: "Descripción",
        qty: "Cant.",
        price: "Precio",
        subtotal: "Subtotal",
        tax: "Impuestos",
        total: "Total",
        thanks: "Gracias por tu negocio.",
        generated: "Generado por Tadeo Invoices",
      }
    : {
        invoice: "INVOICE",
        from: "FROM",
        billTo: "BILL TO",
        issue: "Issue date",
        due: "Due date",
        status: "Status",
        desc: "Description",
        qty: "Qty",
        price: "Price",
        subtotal: "Subtotal",
        tax: "Tax",
        total: "Total",
        thanks: "Thank you for your business.",
        generated: "Generated by Tadeo Invoices",
      };
}

async function loadInvoice(idOrToken: string) {
  let invoiceResult = await supabaseAdmin
    .from("invoices")
    .select("*")
    .eq("id", idOrToken)
    .maybeSingle();

  if (!invoiceResult.data) {
    invoiceResult = await supabaseAdmin
      .from("invoices")
      .select("*")
      .eq("public_token", idOrToken)
      .maybeSingle();
  }

  if (!invoiceResult.data) return null;

  const { data: items } = await supabaseAdmin
    .from("invoice_items")
    .select("*")
    .eq("invoice_id", invoiceResult.data.id);

  return {
    ...invoiceResult.data,
    invoice_items: items || [],
  };
}

export async function GET(
  req: Request,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await context.params;
    const url = new URL(req.url);

    // English by default. Use ?lang=es only if you want Spanish.
    const lang: Lang = url.searchParams.get("lang") === "es" ? "es" : "en";
    const t = copy(lang);

    const invoice = await loadInvoice(id);

    if (!invoice) {
      return NextResponse.json(
        { error: "Invoice not found", id },
        { status: 404 }
      );
    }

    const { data: profile } = await supabaseAdmin
      .from("profiles")
      .select("company_name, company_email, company_phone, company_address")
      .eq("id", invoice.user_id)
      .maybeSingle();

    const currency = invoice.currency || "USD";

    const companyName =
      profile?.company_name || invoice.company_name || "Tadeo Invoices";

    const companyEmail =
      profile?.company_email ||
      invoice.company_email ||
      "billing@tadeoinvoice.com";

    const companyPhone = profile?.company_phone || invoice.company_phone || "";

    const companyAddress =
      profile?.company_address || invoice.company_address || "";

    const items = Array.isArray(invoice.invoice_items)
      ? invoice.invoice_items
      : [];

    const subtotal = Number(invoice.subtotal || invoice.total || 0);
    const tax = Number(invoice.tax_total ?? invoice.tax ?? 0);
    const total = Number(invoice.total || subtotal + tax || 0);

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([612, 792]);

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const navy = rgb(0.02, 0.05, 0.15);
    const blue = rgb(0.15, 0.39, 0.92);
    const light = rgb(0.985, 0.99, 1);
    const line = rgb(0.86, 0.9, 0.95);
    const muted = rgb(0.39, 0.46, 0.57);
    const white = rgb(1, 1, 1);
    const softBlue = rgb(0.93, 0.96, 1);

    page.drawRectangle({
      x: 0,
      y: 0,
      width: 612,
      height: 792,
      color: light,
    });

    page.drawRectangle({
      x: 0,
      y: 720,
      width: 612,
      height: 72,
      color: navy,
    });

    page.drawText(companyName.slice(0, 40), {
      x: 44,
      y: 752,
      size: 18,
      font: bold,
      color: white,
    });

    page.drawText(companyEmail.slice(0, 46), {
      x: 44,
      y: 732,
      size: 10,
      font,
      color: rgb(0.82, 0.88, 1),
    });

    page.drawText(t.invoice, {
      x: 392,
      y: 748,
      size: 34,
      font: bold,
      color: white,
    });

    page.drawText(`#${invoice.invoice_number || invoice.id}`, {
      x: 394,
      y: 726,
      size: 10,
      font,
      color: rgb(0.82, 0.88, 1),
    });

    let topY = 672;

    page.drawText(t.from, {
      x: 44,
      y: topY,
      size: 9,
      font: bold,
      color: blue,
    });

    page.drawText(String(companyName).slice(0, 40), {
      x: 44,
      y: topY - 20,
      size: 14,
      font: bold,
      color: navy,
    });

    page.drawText(String(companyEmail).slice(0, 44), {
      x: 44,
      y: topY - 38,
      size: 10,
      font,
      color: muted,
    });

    if (companyPhone) {
      page.drawText(String(companyPhone).slice(0, 34), {
        x: 44,
        y: topY - 54,
        size: 10,
        font,
        color: muted,
      });
    }

    if (companyAddress) {
      page.drawText(String(companyAddress).slice(0, 58), {
        x: 44,
        y: topY - 70,
        size: 10,
        font,
        color: muted,
      });
    }

    page.drawRectangle({
      x: 332,
      y: 592,
      width: 236,
      height: 88,
      color: white,
      borderColor: line,
      borderWidth: 1,
    });

    page.drawText(t.billTo, {
      x: 352,
      y: 656,
      size: 9,
      font: bold,
      color: blue,
    });

    page.drawText(String(invoice.client_name || "-").slice(0, 30), {
      x: 352,
      y: 636,
      size: 14,
      font: bold,
      color: navy,
    });

    page.drawText(String(invoice.client_email || "-").slice(0, 34), {
      x: 352,
      y: 618,
      size: 10,
      font,
      color: muted,
    });

    page.drawText(`${t.issue}: ${formatDate(invoice.issue_date, lang)}`, {
      x: 352,
      y: 600,
      size: 9,
      font,
      color: muted,
    });

    page.drawText(`${t.due}: ${formatDate(invoice.due_date, lang)}`, {
      x: 456,
      y: 600,
      size: 9,
      font,
      color: muted,
    });

    const status = String(invoice.status || "draft").toUpperCase();

    page.drawRectangle({
      x: 44,
      y: 540,
      width: 524,
      height: 34,
      color: white,
      borderColor: line,
      borderWidth: 1,
    });

    page.drawText(t.status, {
      x: 64,
      y: 553,
      size: 10,
      font: bold,
      color: muted,
    });

    page.drawText(status, {
      x: 130,
      y: 553,
      size: 10,
      font: bold,
      color: status === "PAID" ? rgb(0.05, 0.55, 0.28) : blue,
    });

    let y = 490;

    page.drawRectangle({
      x: 44,
      y,
      width: 524,
      height: 34,
      color: navy,
    });

    page.drawText(t.desc, {
      x: 62,
      y: y + 12,
      size: 10,
      font: bold,
      color: white,
    });

    page.drawText(t.qty, {
      x: 310,
      y: y + 12,
      size: 10,
      font: bold,
      color: white,
    });

    page.drawText(t.price, {
      x: 372,
      y: y + 12,
      size: 10,
      font: bold,
      color: white,
    });

    page.drawText(t.total, {
      x: 500,
      y: y + 12,
      size: 10,
      font: bold,
      color: white,
    });

    y -= 36;

    if (items.length === 0) {
      page.drawRectangle({
        x: 44,
        y: y - 10,
        width: 524,
        height: 34,
        color: white,
        borderColor: line,
        borderWidth: 0.5,
      });

      page.drawText("Invoice", {
        x: 62,
        y: y + 2,
        size: 10,
        font,
        color: navy,
      });

      page.drawText("1", {
        x: 316,
        y: y + 2,
        size: 10,
        font,
        color: muted,
      });

      page.drawText(money(total, currency), {
        x: 360,
        y: y + 2,
        size: 10,
        font,
        color: muted,
      });

      page.drawText(money(total, currency), {
        x: 482,
        y: y + 2,
        size: 10,
        font: bold,
        color: navy,
      });
    } else {
      for (const item of items) {
        const qty = Number(item.quantity ?? item.qty ?? 1);
        const price = Number(item.unit_price ?? item.price ?? 0);
        const lineTotal = Number(
          item.line_total ?? item.total ?? qty * price
        );

        page.drawRectangle({
          x: 44,
          y: y - 10,
          width: 524,
          height: 34,
          color: white,
          borderColor: line,
          borderWidth: 0.5,
        });

        page.drawText(String(item.description || "-").slice(0, 42), {
          x: 62,
          y: y + 2,
          size: 10,
          font,
          color: navy,
        });

        page.drawText(String(qty), {
          x: 316,
          y: y + 2,
          size: 10,
          font,
          color: muted,
        });

        page.drawText(money(price, currency), {
          x: 360,
          y: y + 2,
          size: 10,
          font,
          color: muted,
        });

        page.drawText(money(lineTotal, currency), {
          x: 482,
          y: y + 2,
          size: 10,
          font: bold,
          color: navy,
        });

        y -= 34;

        if (y < 220) break;
      }
    }

    page.drawRectangle({
      x: 330,
      y: 116,
      width: 238,
      height: 120,
      color: softBlue,
      borderColor: rgb(0.72, 0.82, 1),
      borderWidth: 1,
    });

    page.drawText(t.subtotal, {
      x: 350,
      y: 204,
      size: 10,
      font,
      color: muted,
    });

    page.drawText(money(subtotal, currency), {
      x: 456,
      y: 204,
      size: 10,
      font: bold,
      color: navy,
    });

    page.drawText(t.tax, {
      x: 350,
      y: 178,
      size: 10,
      font,
      color: muted,
    });

    page.drawText(money(tax, currency), {
      x: 456,
      y: 178,
      size: 10,
      font: bold,
      color: navy,
    });

    page.drawRectangle({
      x: 350,
      y: 158,
      width: 198,
      height: 1,
      color: line,
    });

    page.drawText(t.total.toUpperCase(), {
      x: 350,
      y: 132,
      size: 13,
      font: bold,
      color: navy,
    });

    page.drawText(money(total, currency), {
      x: 440,
      y: 130,
      size: 18,
      font: bold,
      color: blue,
    });

    page.drawText(t.thanks, {
      x: 44,
      y: 52,
      size: 10,
      font: bold,
      color: navy,
    });

    page.drawText(t.generated, {
      x: 44,
      y: 36,
      size: 8,
      font,
      color: muted,
    });

    const pdfBytes = await pdfDoc.save();
    const pdfBuffer = Buffer.from(pdfBytes);

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="invoice-${
          invoice.invoice_number || invoice.id
        }-${lang}.pdf"`,
      },
    });
  } catch (error) {
    console.error("PDF_ERROR", error);

    return NextResponse.json(
      { error: "Could not generate PDF" },
      { status: 500 }
    );
  }
}